import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';

import 'package:get/get.dart';

import '../controllers/home_controller.dart';

class HomeView extends GetView<HomeController> {
  const HomeView({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Ongkos Kirim Indonesia'),
        centerTitle: true,
      ),
      body: ListView(
        padding: EdgeInsets.all(20),
        children: [
          DropdownSearch<String>(
            popupProps: PopupProps.menu(
              showSearchBox: true,

              // disabledItemFn: (String s) => s.startsWith('S'),
            ),
            items: [
              "Aceh",
              "Sumatera Utara",
              "Sumatera Barat",
              "Riau",
              "Jambi",
              "Bengkulu",
              "Lampung",
              "Bangka Belitung",
              "Kepulauan Riau",
              "DKI Jakarta",
              "Jawa Barat",
              "Jawa Tengah",
              "Jawa Timur",
              "DI Yogyakarta",
              "Banten",
              "Bali",
              "Nusa Tenggara Barat",
              "Nusa Tenggara Timur",
              "Kalimantan Barat",
              "Kalimantan Tengah",
              "Kalimantan Selatan",
              "Kalimantan Timur",
              "Kalimantan Utara",
              "Sulawesi Utara",
              "Sulawesi Tengah",
              "Sulawesi Selatan",
              "Sulawesi Tenggara",
              "Gorontalo",
              "Maluku",
              "Maluku Utara",
              "Papua Barat",
              "Papua"
            ],
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: "Provinsi Asal",
                hintText: "Pilih Provinsi Asal",
              ),
            ),
            onChanged: print,
          ),
          // DropdownSearch<String>.multiSelection(
          //   items: [
          //     "Aceh",
          //     "Sumatera Utara",
          //     "Sumatera Barat",
          //     "Riau",
          //     "Jambi",
          //     "Bengkulu",
          //     "Lampung",
          //     "Bangka Belitung",
          //     "Kepulauan Riau",
          //     "DKI Jakarta",
          //     "Jawa Barat",
          //     "Jawa Tengah",
          //     "Jawa Timur",
          //     "DI Yogyakarta",
          //     "Banten",
          //     "Bali",
          //     "Nusa Tenggara Barat",
          //     "Nusa Tenggara Timur",
          //     "Kalimantan Barat",
          //     "Kalimantan Tengah",
          //     "Kalimantan Selatan",
          //     "Kalimantan Timur",
          //     "Kalimantan Utara",
          //     "Sulawesi Utara",
          //     "Sulawesi Tengah",
          //     "Sulawesi Selatan",
          //     "Sulawesi Tenggara",
          //     "Gorontalo",
          //     "Maluku",
          //     "Maluku Utara",
          //     "Papua Barat",
          //     "Papua"
          //   ],
          //   popupProps: PopupPropsMultiSelection.menu(
          //     showSelectedItems: true,
          //     disabledItemFn: (String s) => s.startsWith('I'),
          //   ),
          //   onChanged: print,
          // )
          DropdownSearch<String>(
            popupProps: PopupProps.menu(
              showSearchBox: true,
              // disabledItemFn: (String s) => s.startsWith('S'),
            ),
            items: [
              "Aceh",
              "Sumatera Utara",
              "Sumatera Barat",
              "Riau",
              "Jambi",
              "Bengkulu",
              "Lampung",
              "Bangka Belitung",
              "Kepulauan Riau",
              "DKI Jakarta",
              "Jawa Barat",
              "Jawa Tengah",
              "Jawa Timur",
              "DI Yogyakarta",
              "Banten",
              "Bali",
              "Nusa Tenggara Barat",
              "Nusa Tenggara Timur",
              "Kalimantan Barat",
              "Kalimantan Tengah",
              "Kalimantan Selatan",
              "Kalimantan Timur",
              "Kalimantan Utara",
              "Sulawesi Utara",
              "Sulawesi Tengah",
              "Sulawesi Selatan",
              "Sulawesi Tenggara",
              "Gorontalo",
              "Maluku",
              "Maluku Utara",
              "Papua Barat",
              "Papua"
            ],
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: "Provinsi Tujuan",
                hintText: "Pilih Provinsi Tujuan",
              ),
            ),
            onChanged: print,
          ),
          DropdownSearch<String>(
            popupProps: PopupProps.menu(
              showSearchBox: true,
              // disabledItemFn: (String s) => s.startsWith('S'),
            ),
            items: [
              "Aceh",
              "Sumatera Utara",
              "Sumatera Barat",
              "Riau",
              "Jambi",
              "Bengkulu",
              "Lampung",
              "Bangka Belitung",
              "Kepulauan Riau",
              "DKI Jakarta",
              "Jawa Barat",
              "Jawa Tengah",
              "Jawa Timur",
              "DI Yogyakarta",
              "Banten",
              "Bali",
              "Nusa Tenggara Barat",
              "Nusa Tenggara Timur",
              "Kalimantan Barat",
              "Kalimantan Tengah",
              "Kalimantan Selatan",
              "Kalimantan Timur",
              "Kalimantan Utara",
              "Sulawesi Utara",
              "Sulawesi Tengah",
              "Sulawesi Selatan",
              "Sulawesi Tenggara",
              "Gorontalo",
              "Maluku",
              "Maluku Utara",
              "Papua Barat",
              "Papua"
            ],
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: "Kota Asal",
                hintText: "Pilih Kota Asal",
              ),
            ),
            onChanged: print,
          ),
          DropdownSearch<String>(
            popupProps: PopupProps.menu(
              showSearchBox: true,
              // disabledItemFn: (String s) => s.startsWith('S'),
            ),
            items: [
              "Aceh",
              "Sumatera Utara",
              "Sumatera Barat",
              "Riau",
              "Jambi",
              "Bengkulu",
              "Lampung",
              "Bangka Belitung",
              "Kepulauan Riau",
              "DKI Jakarta",
              "Jawa Barat",
              "Jawa Tengah",
              "Jawa Timur",
              "DI Yogyakarta",
              "Banten",
              "Bali",
              "Nusa Tenggara Barat",
              "Nusa Tenggara Timur",
              "Kalimantan Barat",
              "Kalimantan Tengah",
              "Kalimantan Selatan",
              "Kalimantan Timur",
              "Kalimantan Utara",
              "Sulawesi Utara",
              "Sulawesi Tengah",
              "Sulawesi Selatan",
              "Sulawesi Tenggara",
              "Gorontalo",
              "Maluku",
              "Maluku Utara",
              "Papua Barat",
              "Papua"
            ],
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: "Kota Asal",
                hintText: "Pilih Kota Asal",
              ),
            ),
            onChanged: print,
          ),
        ],
      ),
    );
  }
}
